# Project: 飞机大战
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o
LINKOBJ  = main.o
LIBS     = -L"D:/chenkaiquan/Dev-Cpp/MinGW64/lib" -L"D:/chenkaiquan/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -lgraphics64 -luuid -lmsimg32 -lgdi32 -limm32 -lole32 -loleaut32 -lwinmm -luuid -mwindows
INCS     = -I"D:/chenkaiquan/Dev-Cpp/MinGW64/include" -I"D:/chenkaiquan/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/chenkaiquan/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/chenkaiquan/Dev-Cpp/MinGW64/include" -I"D:/chenkaiquan/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/chenkaiquan/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/chenkaiquan/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = 飞机大战（夏日清凉版）.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)
